[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Libraries
lib_deps = 
    bblanchon/ArduinoJson@^7.2.1
    links2004/WebSockets@^2.5.4

; Serial monitor
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

; Upload
;upload_speed = 921600     ; optional — drop to 115200 if unstable

; Build flags
build_flags = -DCORE_DEBUG_LEVEL=0   ; suppress Arduino core debug logs